### ISSUE TITLE
games-emulation/citra-libretro-1.0_pre20171111 fails to build.

### ISSUE THREAD

**Issue by crocket** [stefan-gr/abendbrot#100]
```
 * Messages for package games-emulation/citra-libretro-1.0_pre20171111:

 * ERROR: games-emulation/citra-libretro-1.0_pre20171111::abendbrot failed (unpack phase):
 *   Referencing 4b0ec7ec21b2c3fdaa2b9a32426d44ade6926539 failed (wrong ref?).
```

I suspect every version of citra-libretro doesn't build because the git repository has probably been rebased.

**Comment by stefan-gr** [comment]
The non-live builds should work now but I have no idea why 9999 fails. I would just delete the git-src from this ebuild in ${DISTDIR}/git3-src and try fetching anew.

**Comment by crocket** [comment]
games-emulation/citra-libretro-1.0_pre20170916

```
 * Checking out https://github.com/fmtlib/fmt.git to /var/tmp/portage/games-emulation/citra-libretro-1.0_pre20170916/work/citra-libretro-1.0_pre20170916/externals/dynarmic/externals/fmt ...
git checkout --quiet 7e00cea85e24f836f86e715acd1d07128512acb4
fatal: Cannot switch branch to a non-commit '7e00cea85e24f836f86e715acd1d07128512acb4'
 * ERROR: games-emulation/citra-libretro-1.0_pre20170916::abendbrot failed (unpack phase):
 *   git checkout 7e00cea85e24f836f86e715acd1d07128512acb4 failed
```

games-emulation/citra-libretro-1.0_pre20171111

```
 * Checking out https://github.com/fmtlib/fmt.git to /var/tmp/portage/games-emulation/citra-libretro-1.0_pre20171111/work/citra-libretro-1.0_pre20171111/externals/dynarmic/externals/fmt ...
git checkout --quiet 7e00cea85e24f836f86e715acd1d07128512acb4
fatal: Cannot switch branch to a non-commit '7e00cea85e24f836f86e715acd1d07128512acb4'
 * ERROR: games-emulation/citra-libretro-1.0_pre20171111::abendbrot failed (unpack phase):
 *   git checkout 7e00cea85e24f836f86e715acd1d07128512acb4 failed
```

games-emulation/citra-libretro-9999-r2

```
 * Checking out https://github.com/fmtlib/fmt.git to /var/tmp/portage/games-emulation/citra-libretro-9999-r2/work/citra-libretro-9999/externals/dynarmic/externals/fmt ...
git checkout --quiet 7e00cea85e24f836f86e715acd1d07128512acb4
fatal: Cannot switch branch to a non-commit '7e00cea85e24f836f86e715acd1d07128512acb4'
 * ERROR: games-emulation/citra-libretro-9999-r2::abendbrot failed (unpack phase):
 *   git checkout 7e00cea85e24f836f86e715acd1d07128512acb4 failed
```

**Comment by stefan-gr** [comment]
Did you delete /usr/portage/distfiles/git3-src beforehand? Those commits aren't up-to-date since long ago so I think you are still on the old src.

**Comment by crocket** [comment]
I deleted everything in `/usr/portage/distfiles/git3-src`. I still see the same error.

```
 * Checking out https://github.com/fmtlib/fmt.git to /var/tmp/portage/games-emulation/citra-libretro-1.0_pre20171111/work/citra-libretro-1.0_pre20171111/externals/dynarmic/externals/fmt ...
git checkout --quiet 7e00cea85e24f836f86e715acd1d07128512acb4
fatal: Cannot switch branch to a non-commit '7e00cea85e24f836f86e715acd1d07128512acb4'
 * ERROR: games-emulation/citra-libretro-1.0_pre20171111::abendbrot failed (unpack phase):
 *   git checkout 7e00cea85e24f836f86e715acd1d07128512acb4 failed
```

**Comment by stefan-gr** [comment]
That's strange, I found out why that happens on older builds. but it shouldn't happen with 9999 anymore. I just did a crude bump to the latest commit.

**Comment by crocket** [comment]
```
 * Checking out https://github.com/fmtlib/fmt.git to /var/tmp/portage/games-emulation/citra-libretro-1.0_pre20180314/work/citra-libretro-1.0_pre20180314/externals/dynarmic/externals/fmt ...
git checkout --quiet 7e00cea85e24f836f86e715acd1d07128512acb4
fatal: Cannot switch branch to a non-commit '7e00cea85e24f836f86e715acd1d07128512acb4'
 * ERROR: games-emulation/citra-libretro-1.0_pre20180314::abendbrot failed (unpack phase):
 *   git checkout 7e00cea85e24f836f86e715acd1d07128512acb4 failed
```

**Comment by stefan-gr** [comment]
I would need to test this on gentoo to further troubleshoot this.
I can't even find out where git-r3 gets `7e00cea85e24f836f86e715acd1d07128512acb4`. None of the submodules have this commit and never had, according to github history. Also, /externals/dynarmic/externals/fmt isn't even a submodule. Only dynarmic is one and that also has no mention of that commit  git wants to checkout.
I'm sorry, but I have to leave this as is until I can see if it is reproducible on my next gentoo rig. 

As a side note, using `git clone --recurse-submodules `has no problems with this repo, it seems that git-r3 just does something different with the submodules that we have to account for.

**Comment by Jannis234** [comment]
It's reproducible for me and I actually ran into the same problem while packaging the stand alone version of citra in my overlay (https://github.com/Jannis234/jm-overlay/blob/master/games-emulation/citra/citra-9999.ebuild).
I don't exactly remember where that commit ID came from but the problem seems to be that the submodules "fmtlib" and "xbyak" are used by both citra and dynarmic (at least in the citra-HEAD), which somehow confuses git-r3.
My fix was to exclude the duplicates from EGIT_SUBMODULES and copy the directories manually in src_unpack.

**Comment by stefan-gr** [comment]
Whew, thanks for this information @Jannis234 . I just copy/pasted your modifications and hope that it works now.
